name: CI Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-node@v2.5.0
        with:
          node-version: '17'
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: '2.7.7'
      - name: Vendor Cache
        id: vendor-cache
        uses: zendesk/cache@v2
        with:
          path: vendor/cache
          key: ${{ runner.os }}-vendor
      - name: Install compatible ffi Ruby gem
        run: gem install ffi -v 1.16.0
      - name: Install compatible hitimes Ruby gem
        run: gem install hitimes -v 2.0.0
      - run: gem install zendesk_apps_tools
      - run: zat translate to_json --path=./src
      - run: cat ./src/translations/en.json
      - run: npm install
      - run: npm run build
